name: CI

on:
  push:
    branches:
     - main
  pull_request:
    branches:
     - main
     
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps: 
     - name: Chechout code
       uses: actions/checkout@v2
       
     - name: Set up Python
       uses: action/setup-python@v2
       with: 
       	python-version: 3.8 

     - name: Install dependencies
       run: | 
         python -m venv venv
         source venv/bin/activate
         pip install -r requirements.txt
         
     - name: Lint with flake8
       run: |
         source venv/bin/activate
         flake8 .
         
     - name: Test with pytest
       run: |
         source venv/bin/activate
         pytest
         
    - name: Security checj with Bandit
      run: |
        source venv/bin/activate
        bandit -r app
        
    - name: Dependency check with Safety
      run: |
        source venv/bin/activate
        safety check
         
